version: "3"
services:
  app:
    image: spurin/hexo
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      NODE_ENV: development
    ports:
      - 4000:4000
    # command: npm install && hexo
